### ISSUE TITLE
Game crashes when running the mod from IDE

### ISSUE THREAD

**Issue by ItsIlya** [Gunpowder-MC/Gunpowder#82]
**Information**
- Minecraft Version: 1.16.2
- Fabric API Version: 0.17.2+build.396-1.16
- OS: Windows
- Other installed mods: []

**Describe the issue**
The game crashes on launch from the IDE.

**Crash logs**
https://hastebin.com/owikuzewoy.sql

**To Reproduce**
1. Run or Start Debugging the project in the IDE.
2. See error.

**Comment by MaryWeeb** [comment]
Use the jars from curseforge, as maven jars exclude dependencies.
This may get updated later to include dependencies, but will quickly increase load on our maven host. Needs internal discussion.

---

*After we use the full jars on maven*
This is an issue caused by Loom, as the following happens:

- We use library Exposed
    - Exposed loads Kotlin (from standard classloader)
- We use fabric language kotlin
    - FLK loads Kotlin (from knotclassloader)

Kotlin is now loaded on different classloaders, resulting in exceptions when trying to load.
