### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by srnyx** [Gunpowder-MC/Gunpowder#95]
**Information**
- Minecraft Version: 1.16.5
- Fabric API Version: 0.32.0
- OS: Debian, OpenJDK 11
- Other installed mods: https://www.curseforge.com/minecraft/modpacks/simpearth

**Describe the issue**
Server crashes with the latest version (0.3.7)

**Crash/Error logs**
https://pastebin.com/puB44XHj

**To Reproduce**
1. Use the latest mod version on 1.16.5

**Expected behavior**
Server should start

**Comment by martmists-gh** [comment]
Remove Carpet, it breaks many other mods.

**Comment by srnyx** [comment]
> Remove Carpet, it breaks many other mods.

But I use Carpet for a ton of things.

**Comment by martmists-gh** [comment]
Carpet makes too many changes in incompatible ways that many mods will have issues with it. I'm not willing to add support for carpet, and I doubt they're willing to add support for Gunpowder. You'll have to remove either Carpet or Gunpowder sadly.

**Comment by altrisi** [comment]
Does it cause really cause that many issues? (first time I hear that, would love to know more)

BTW, the only thing that seems to be failing here is the `isDebugEnabled` redirect in CommandManager, which I guess either Carpet or Gunpowder could easily convert to a require 0 (maybe even both?), since I don't think it is required functionality in any of them. One could also argue that here Gunpowder is the cause, since it is also redirecting a method that other mods may want to redirect, I'd say both are doing the same.

As a workaround, users can use a version older than commit b4e315f317e4c748760d3c473082f6a50ecf975e (4 days ago) to prevent the conflict, or manually remove/disable the mixin if they know how to.

**Comment by martmists-gh** [comment]
If the issues arises with another mod I'll fix it, but carpet is known to cause many incompatibilities and as such I won't be adding support for it.

**Comment by altrisi** [comment]
Should be fixed in the latest Carpet build, unless Loader/Mixin decides to load Carpet's mixin before Gunpowder's (since Gunpowder is requiring the command stacktrace mixin), which doesn't seem to be the case (was mod loading order arbitrary or did I make that up?).

**Comment by srnyx** [comment]
> Should be fixed in the latest Carpet build, unless Loader/Mixin decides to load Carpet's mixin before Gunpowder's (since Gunpowder is requiring the command stacktrace mixin), which doesn't seem to be the case (was mod loading order arbitrary or did I make that up?).
> 
> BTW this technically makes Gunpowder incompatible with WDMCF.

Wait so it should be working now using Carpet v1.4.29?

**Comment by altrisi** [comment]
Build, not release (it should work in next release). You can get those in Github actions, check the comment in the Carpet issue linked in this conversation.

**Comment by srnyx** [comment]
> Build, not release (it should work in next release, which is probably tomorrow if there's a snapshot). You can get those in Github actions, check the comment in the Carpet issue linked in this conversation.
> 
> Edit: For convenience: https://github.com/gnembon/fabric-carpet/actions/runs/658057389
> Go to artifacts, then in the zip, the jar that doesn't end with neither `-dev` or `-sources`

Alright, thank you!
